### ISSUE TITLE
Restart processing without disposing 

### ISSUE THREAD

**Issue by markpjohnson** [james-hu/jabb-core-java8#7]
I am following the process on your [wiki ](https://github.com/james-hu/jabb-core-java8/wiki/Java%20equivalent%20of%20EventProcessorHost%20for%20processing%20events%20in%20Azure%20Event%20Hub). If my process quits unexpectedly without performing step 7, are there any adverse side effects? 

I haven't noticed side effects any. So far, it seems like checkpointing still works as expected, but I wanted to check if there was anything that I am missing.

**Comment by james-hu** [comment]
It depends on how you define "my process quits". If it means the application crashes (kill -9 or power down) which is the worst case. You are right, the transactions will just time out and be picked up by another instance of the application (if you relaunch the application) later. 

But in general, if you want to stop processing while keeping other parts of your application still running, you'd better stop all the processors and shutdown the thread pool properly just for keeping JVM healthy.

**Comment by markpjohnson** [comment]
Thanks! That makes sense.
